Neos:
  Flow:
    reflection:
      ignoredTags:
        'phpcsSuppress': TRUE

#Flowpack:
#  JobQueue:
#    Common:
#      queues:
#        #
#        # This is a sample configuration that shows all possible configuration options and
#        # their defaults
#        #

#        demo:
#          className: 't3n\JobQueue\RabbitMQ\Queue\RabbitQueue'
#          executeIsolated: true
#          maximumNumberOfReleases: 3
#
#          releaseOptions:
#            delay: 5
#
#          options:
#            routingKey: '' # for advanced exchange configuration
#            useDLX: false # support for dead letter exchange
#
#            # Options that are used to configure a queue
#            queueOptions:
#              declare: true
#              exchangeName: ''
#              passive: false
#              durable: false
#              exclusive: false
#              autoDelete: true
#              nowait: false
#              arguments: []
#              ticket: null
#
#            # Options to configure an optional exchange
#            exchange:
#              declare: true
#              name: 't3n-exchange' # this field cannot be blank as the default exchange can not be overriden!
#              type: 'direct'
#              passive: false
#              durable: false
#              autoDelete: true
#              internal: false
#              nowait: false
#              arguments: []
#
#            client:
#              host: localhost
#              port: 5672
#              username: guest
#              password: guest
#              vhost: '/'
#              insist: false
#              loginMethod: 'AMQPLAIN'
